name: Enhancement Request
description: Propose an improvement to an existing Audemy feature
title: '[ENHANCEMENT]: '
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: "## 🔧 Enhancement Request\nUse this form to improve existing features in Audemy."

  - type: textarea
    id: current
    attributes:
      label: What feature are you enhancing?
      placeholder: 'Describe the current feature.'
    validations:
      required: true

  - type: textarea
    id: improvement
    attributes:
      label: What improvement would you like to see?
      placeholder: 'Explain what should be improved and why.'
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: How will this benefit users?
      placeholder: 'Tell us how this improves user experience or functionality.'

  - type: checkboxes
    id: confirm
    attributes:
      label: Before submitting
      options:
        - label: I’ve checked for similar enhancement requests.
          required: true
