export const gameConfigs = {
  addition: {
    title: 'Animal Addition',
    description: 'Add up the animals!',
    bgColor: '#FFBCEE',
    iconSrc: '/assets/gameImages/buttons/gameButtons/addition.svg',
    introAudio: '/animalAddition/additionintro.mp3',
    dbFile: 'additionDb.json',
    dbKey: 'AdditionGame',
    category: 'math',
  },

  colorGame: {
    title: 'Color Game',
    description: 'Name the color of a given object!',
    bgColor: '#EACAFF',
    iconSrc: '/assets/gameImages/buttons/gameButtons/color-game.svg',
    introAudio: '/colorGame/colorIntro.mp3',
    dbFile: 'crazyColorsDB.json',
    dbKey: 'ColorQuizGame',
    category: 'language',
  },

  definitionDetective: {
    title: 'Definition Detective',
    description: 'Find the correct word based on the definition.',
    bgColor: '#9AE2EB',
    iconSrc: '/assets/gameImages/buttons/gameButtons/definition.svg',
    introAudio: '/definitionDetective/definitionIntro.mp3',
    dbFile: 'definitionDetectiveDB.json',
    dbKey: 'DefinitionDetectiveGame',
    category: 'language',
  },

  division: {
    title: 'Division Duel',
    description: 'Divide the given numbers!',
    bgColor: '#6FFFC6',
    iconSrc: '/assets/gameImages/buttons/gameButtons/div.svg',
    introAudio: '/divisionduel/divintro.mp3',
    dbFile: 'divisionDb.json',
    dbKey: 'DivisionGame',
    category: 'math',
  },

  fruitFrenzy: {
    title: 'Fruit Frenzy',
    description: 'How many total fruits are there?',
    bgColor: '#FFC5C5',
    iconSrc: '/assets/gameImages/buttons/gameButtons/ff.svg',
    introAudio: '/fruitFrenzy/fruitIntro.mp3',
    dbFile: 'fruitFrenzy.json',
    dbKey: 'FruitFrenzy',
    category: 'math',
  },

  monkeyMadness: {
    title: 'Monkey Madness',
    description: 'Help the monkeys split their bananas!',
    bgColor: '#F9AEB0',
    iconSrc: '/assets/gameImages/buttons/gameButtons/mm.svg',
    introAudio: '/monkeyMadness/monkeyintro.mp3',
    dbFile: 'monkeyMadnessDB.json',
    dbKey: 'MonkeyMadnessGame',
    category: 'math',
  },

  multiplication: {
    title: 'Multiplication Madness',
    description: 'Can you multiply numbers?',
    bgColor: '#AEB9FF',
    iconSrc: '/assets/gameImages/buttons/gameButtons/mul.svg',
    introAudio: '/multiplicationmadness/multiplicationintro.mp3',
    dbFile: 'multiplication.json',
    dbKey: 'MultiplicationGame',
    category: 'math',
  },

  oddOneOut: {
    title: 'Odd One Out',
    description: "Can you find what doesn't belong?",
    bgColor: '#FFD2F4',
    iconSrc: '/assets/gameImages/buttons/gameButtons/oddOneOut.svg',
    introAudio: '/oddoneout/oddoneoutintro.mp3',
    dbFile: 'oddOneOutDB.json',
    dbKey: 'OddOneOutGame',
    category: 'language',
  },

  partOfSpeech: {
    title: 'Part of Speech',
    description: 'Noun, verb, or adjective?',
    bgColor: '#6FFFC6',
    iconSrc: '/assets/gameImages/buttons/gameButtons/pos.svg',
    introAudio: '/partOfSpeech/partofspeechintro.mp3',
    dbFile: 'partOfSpeechDB.json',
    dbKey: 'PartOfSpeechGame',
    category: 'language',
  },

  polarPairing: {
    title: 'Polar Pairing',
    description: 'Test your vocabulary with polar opposites.',
    bgColor: '#EAD2B0',
    iconSrc: '/assets/gameImages/buttons/gameButtons/strawberry.svg',
    introAudio: '/polarpairing/oppintro.mp3',
    dbFile: 'polarPairingDB.json',
    dbKey: 'PolarPairingGame',
    category: 'language',
  },

  shapeShark: {
    title: 'Shape Shark',
    description: 'Identify the shape based on its sides.',
    bgColor: '#8FD5F8',
    iconSrc: '/assets/gameImages/buttons/gameButtons/ss.svg',
    introAudio: '/shapeSharks/shapeintro.mp3',
    dbFile: 'shapeSharkDB.json',
    dbKey: 'ShapeSharkGame',
    category: 'math',
  },

  spellingBee: {
    title: 'Spelling Bee',
    description: 'Buzz your way to spelling mastery!',
    bgColor: '#FAE9B6',
    iconSrc: '/assets/gameImages/buttons/gameButtons/spellingBee.svg',
    introAudio: '/spellingBee/spellingintro.mp3',
    dbFile: 'spellingBeeDB.json',
    dbKey: 'SpellingBeeGame',
    category: 'language',
  },

  subtraction: {
    title: 'Subtraction Safari',
    description: 'Subtract animals in safari scenarios!',
    bgColor: '#9AE2EB',
    iconSrc: '/assets/gameImages/buttons/gameButtons/subtraction.svg',
    introAudio: '/subtractionSafari/subtractionintro.mp3',
    dbFile: 'subtractionDB.json',
    dbKey: 'SubtractionGame',
    category: 'math',
  },
};
